import path from 'path';

function readNumber(name: string, fallback: number): number {
  const raw = process.env[name];
  if (!raw) return fallback;
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function readCorsOrigins(): string[] | '*' {
  const raw = process.env.CORS_ORIGINS?.trim();
  if (!raw || raw === '*') return '*';
  return raw.split(',').map((origin) => origin.trim()).filter(Boolean);
}

export const config = {
  port: readNumber('PORT', 5180),
  host: process.env.HOST || '0.0.0.0',
  databasePath: path.resolve(process.env.DATABASE_PATH || './data/gateway.sqlite'),
  jsonBodyLimit: process.env.JSON_BODY_LIMIT || '50mb',
  stationApiToken: process.env.STATION_API_TOKEN || '',
  corsOrigins: readCorsOrigins(),
  publicBaseUrl: process.env.PUBLIC_BASE_URL || '',
  requestRetentionDays: readNumber('REQUEST_RETENTION_DAYS', 30),
};

export function validateConfig() {
  if (!config.stationApiToken || config.stationApiToken === 'replace-with-station-generated-token') {
    throw new Error('STATION_API_TOKEN must be set to the token generated by KaraokeDock Station.');
  }
}
